name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🎉
        
        Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: This feature doesn't already exist in the application
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see
      placeholder: Provide a concise summary of the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is.
        Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        A clear and concise description of what you want to happen.
        Include any specific requirements or constraints.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        A clear and concise description of any alternative solutions 
        or features you've considered.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Important for productivity
        - Critical - Blocking current work
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component Area
      description: Which area of the application would this feature affect?
      options:
        - Authentication & Authorization
        - Product Management
        - Media Management
        - User Management
        - Analytics & Reporting
        - API & Integrations
        - Database & Data Models
        - UI/UX & Design
        - Performance & Optimization
        - Security
        - Testing & Quality
        - DevOps & Infrastructure
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: User Type
      description: Who would primarily benefit from this feature?
      multiple: true
      options:
        - Admin Users
        - Content Editors
        - API Consumers
        - Developers
        - End Users
        - System Administrators

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Write a user story for this feature
      placeholder: |
        As a [type of user], 
        I want [some goal] 
        so that [some reason/benefit].
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What criteria must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Wireframes
      description: If applicable, add mockups, wireframes, or examples
      placeholder: Drag and drop images here or paste URLs to mockups...

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Any technical aspects or constraints to consider?
      placeholder: |
        - Database changes required
        - API modifications needed
        - Performance implications
        - Security considerations
        - Third-party integrations

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Scope
      description: What would this feature require? (Check all that apply)
      options:
        - label: Frontend UI changes
        - label: Backend API changes
        - label: Database schema changes
        - label: New dependencies
        - label: Configuration changes
        - label: Documentation updates
        - label: Testing updates

  - type: textarea
    id: business-value
    attributes:
      label: Business Value
      description: What business value would this feature provide?
      placeholder: |
        - Increased user productivity
        - Improved user experience
        - Cost savings
        - Revenue opportunities
        - Competitive advantage

  - type: input
    id: timeline
    attributes:
      label: Desired Timeline
      description: When would you like to see this feature implemented?
      placeholder: e.g., Next release, Q2 2024, No specific timeline

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: |
        Any additional information that would help understand 
        or implement this feature...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I can help with requirements gathering
        - label: I can help with design/mockups
        - label: I can help with implementation
        - label: I can help with testing
        - label: I can help with documentation